spring:
  profiles:
    active: dev
  application:
    name: auth-service
  server:
    port: 8080
  security:
    oauth2:
      client:
        provider:
          custom-provider:
            user-info-url: /api/getLoginUser

